### ISSUE TITLE
No module named webvirtmgr.settings

### ISSUE THREAD

**Issue by Zermond** [retspen/webvirtmgr#460]
Привет. Подскажи, пожалуйста, почему я получаю эту ошибку?
if I run ./manage.py runserver 0:8000 I see this error:

Traceback (most recent call last):
File "./manage.py", line 10, in 
execute_from_command_line(sys.argv)
File "/usr/lib/python2.7/site-packages/django/core/management/init.py", line 453, in execute_from_command_line
utility.execute()
File "/usr/lib/python2.7/site-packages/django/core/management/init.py", line 392, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/usr/lib/python2.7/site-packages/django/core/management/init.py", line 263, in fetch_command
app_name = get_commands()[subcommand]
File "/usr/lib/python2.7/site-packages/django/core/management/init.py", line 109, in get_commands
apps = settings.INSTALLED_APPS
File "/usr/lib/python2.7/site-packages/django/conf/init.py", line 53, in getattr
self.setup(name)
File "/usr/lib/python2.7/site-packages/django/conf/__init_.py", line 48, in setup
self.wrapped = Settings(settings_module)
File "/usr/lib/python2.7/site-packages/django/conf/__init.py", line 134, in init
raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'webvirtmgr.settings' (Is it on sys.path?): No module named webvirtmgr.settings

uname -a:
Linux zermond 3.16.4-200.fc20.x86_64 #1 SMP Mon Oct 6 12:57:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Fedora 20

**Comment by lun2lan** [comment]
Requirement already satisfied (use --upgrade to upgrade): django==1.5.5 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): gunicorn==18.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): lockfile>=0.9 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5))
[root@trend-maxx webvirtmgr]#  pip install lockfile
Requirement already satisfied (use --upgrade to upgrade): lockfile in /usr/lib/python2.7/site-packages
[root@trend-maxx webvirtmgr]# ./manage.py runserver 192.168.20.254:8000
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 263, in fetch_command
    app_name = get_commands()[subcommand]
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 134, in __init__
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'webvirtmgr.settings' (Is it on sys.path?): No module named webvirtmgr.settings

**Comment by sammcj** [comment]
Where is your local settings file?

Have a look at https://github.com/retspen/webvirtmgr/blob/master/webvirtmgr/local/local_settings.py.example

Rename that to remove .example and fill in as required (if at all)
Then you can `./manage.py syncdb --settings=webvirtmgr.local.local_settings`
