### ISSUE TITLE
cant get console access to guests

### ISSUE THREAD

**Issue by poxus** [retspen/webvirtmgr#480]
hi again!
I can't get console access to Guests. There are see some errors in webmgr-novnc.log and supervisord.log.

supervisord.log:
2014-12-10 12:45:14,380 INFO daemonizing the supervisord process
2014-12-10 12:45:14,381 INFO supervisord started with pid 5936
2014-12-10 12:45:15,384 INFO spawned: 'webvirtmgr' with pid 5937
2014-12-10 12:45:15,385 INFO spawned: 'webvirtmgri-novnc' with pid 5938
2014-12-10 12:45:15,498 INFO exited: webvirtmgri-novnc (exit status 1; not expected)
2014-12-10 12:45:16,738 INFO success: webvirtmgr entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2014-12-10 12:45:16,739 INFO spawned: 'webvirtmgri-novnc' with pid 5947
2014-12-10 12:45:16,852 INFO exited: webvirtmgri-novnc (exit status 1; not expected)
2014-12-10 12:45:18,855 INFO spawned: 'webvirtmgri-novnc' with pid 5951
2014-12-10 12:45:18,967 INFO exited: webvirtmgri-novnc (exit status 1; not expected)

webvirtmgr-novnc.log:
WARNING:root:No local_settings file found.
WebSocket server settings:
- Listen on 0.0.0.0:6080
- Flash security policy server
- SSL/TLS support
  Traceback (most recent call last):
  File "/var/www/webvirtmgr/console/webvirtmgr-novnc", line 160, in <module>
    server.start_server()
  File "/usr/lib/python2.7/dist-packages/novnc/websocket.py", line 760, in start_server
    lsock = self.socket(self.listen_host, self.listen_port)
  File "/usr/lib/python2.7/dist-packages/novnc/websocket.py", line 170, in socket
    sock.bind(addrs[0][4])
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
  socket.error: [Errno 98] Address already in use

**Comment by brenard** [comment]
Hello, 

Check if you have novnc service install. This service run by default on the same port. You have to disable it as explain in the installation doc.
