### ISSUE TITLE
Internal server error, when select instance

### ISSUE THREAD

**Issue by zsirmo** [retspen/webvirtmgr#487]
Hy,

I have a problem with newly installed instance
Log:
ERROR:django.request:Internal Server Error: /instance/1/tesztdb/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/var/www/webvirtmgr/instance/views.py", line 421, in instance
    networks = conn.get_net_device()
  File "/var/www/webvirtmgr/vrtManager/instance.py", line 190, in get_net_device
    return util.get_xml_path(self._XMLDesc(0), func=networks)
  File "/var/www/webvirtmgr/vrtManager/util.py", line 104, in get_xml_path
    result = func(ctx)
  File "/var/www/webvirtmgr/vrtManager/instance.py", line 181, in networks
    nic_host = net.xpathEval('source/@network|source/@bridge|source/@dev')[0].content
IndexError: list index out of range

Regards Attila

**Comment by n1ywb** [comment]
I also am having this issue, following a webvirtmgr restart. I found I was able to work around it by shutting down and cold booting my guests.
