### ISSUE TITLE
Usage statistics 500 error

### ISSUE THREAD

**Issue by Aidenir** [retspen/webvirtmgr#493]
I'm having problems getting the usage statistics to work, both in the overview an in specific VM:s.
When running in Debug mode I get this error on every ajax call in the log:

```
Internal Server Error: /info/instusage/5/NAS/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/http/webvirtmgr/instance/views.py", line 69, in instusage
    cookies['cpu'] = request._cookies['cpu']
AttributeError: 'WSGIRequest' object has no attribute '_cookies'
ERROR:django.request:Internal Server Error: /info/instusage/5/NAS/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/http/webvirtmgr/instance/views.py", line 69, in instusage
    cookies['cpu'] = request._cookies['cpu']
AttributeError: 'WSGIRequest' object has no attribute '_cookies'
```

**Comment by brenard** [comment]
Cookies access method seem to be incorrect in instusage() method. I fix it in https://github.com/brenard/webvirtmgr/commit/1391692162eb42293eaa41f809800049578d3ecc.

**Comment by Aidenir** [comment]
When I try to use @brenard 's fork I instead get this
````

ERROR:django.request:Internal Server Error: /info/instusage/1/NAS/
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/http/webvirtmgr2/instance/views.py", line 68, in instusage
    cookies = request._get_cookies()
AttributeError: 'WSGIRequest' object has no attribute '_get_cookies'

````

**Comment by brenard** [comment]
I mean you are not using the good version of Django. Could you check that the version install on your host is 1.5.5 ?

```
$ python 
Python 2.7.3 (default, Mar 13 2014, 11:03:55) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import django
>>> django.get_version()
'1.5.5'
```

**Comment by Aidenir** [comment]
Apparantly I have 1.7.3 installed. I will try to install and use 1.5.5 when I get of work tonight.

**Comment by Aidenir** [comment]
When I installed 1.5.5 it shows the usage graphs. Thanks for the help
