### ISSUE TITLE
Webvirtmgr crashes if domain not found

### ISSUE THREAD

**Issue by sammcj** [retspen/webvirtmgr#527]
I deleted the disk for a VM, then went to delete the VM, but I can't because it has no disk:

```
libvirt: QEMU Driver error : Domain not found: no domain with matching name 'Win7'
ERROR:django.request:Internal Server Error: /info/instusage/1/Win7/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/var/www/webvirtmgr/instance/views.py", line 201, in instusage
    for i, net in enumerate(networks):
TypeError: 'NoneType' object is not iterable
192.168.0.20 - - [19/Mar/2015:11:29:55] "GET /info/instusage/1/Win7/ HTTP/1.0" 500 - "http://192.168.0.71/instance/1/Win7/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:37.0) Gecko/20100101 Firefox/37.0"
INFO:gunicorn.access:192.168.0.20 - - [19/Mar/2015:11:29:55] "GET /info/instusage/1/Win7/ HTTP/1.0" 500 - "http://192.168.0.71/instance/1/Win7/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:37.0) Gecko/20100101 Firefox/37.0"
libvirt: QEMU Driver error : Domain not found: no domain with matching name 'Win7'
ERROR:django.request:Internal Server Error: /instance/1/Win7/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/var/www/webvirtmgr/instance/views.py", line 445, in instance
    instance = Instance(compute_id=host_id, name=vname, uuid=uuid)
UnboundLocalError: local variable 'uuid' referenced before assignment
192.168.0.20 - - [19/Mar/2015:11:29:59] "POST /instance/1/Win7/ HTTP/1.0" 500 - "http://192.168.0.71/instance/1/Win7/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:37.0) Gecko/20100101 Firefox/37.0"
INFO:gunicorn.access:192.168.0.20 - - [19/Mar/2015:11:29:59] "POST /instance/1/Win7/ HTTP/1.0" 500 - "http://192.168.0.71/instance/1/Win7/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:37.0) Gecko/20100101 Firefox/37.0"
```

**Comment by sammcj** [comment]
ty @retspen
