### ISSUE TITLE
archlinux yaourt post-installation help

### ISSUE THREAD

**Issue by v1k0d3n** [retspen/webvirtmgr#552]
I really would like to use this tool on my arch linux platform, however i'm running into an error where these instructions given:

<pre> 
To finalize the installation you need to run:

    # sudo python2 /usr/lib/webvirtmgr/manage.py syncdb
    # chown webvirtmgr:webvirtmgr /usr/lib/webvirtmgr/webvirtmgr/local/.secret_key_store /usr/lib/webvirtmgr/webvirtmgr.sqlite3 /usr/lib/webvirtmgr # temporary, see https://github.com/retspen/webvirtmgr/issues/391
    # sudo python2 /usr/lib/webvirtmgr/manage.py collectstatic
</pre>

<pre>
[root@archserver ~]# sudo python2 /usr/lib/webvirtmgr/manage.py syncdb
WARNING:root:No local_settings file found.
Traceback (most recent call last):
  File "/usr/lib/webvirtmgr/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/webvirtmgr/webvirtmgr/settings.py", line 185, in <module>
    from webvirtmgr.utils import secret_key
  File "/usr/lib/webvirtmgr/webvirtmgr/utils/secret_key.py", line 16, in <module>
    import lockfile
ImportError: No module named lockfile
[root@archserver ~]# 
</pre>

**Comment by brenard** [comment]
Hi, 

Lockfile python lib is missing. You forgot to run _sudo pip install -r requirements.txt_ (refer installation guide in wiki).

**Comment by v1k0d3n** [comment]
i used yaourt in arch linux for the installation. there is no pip command, so i don't think everything is being loaded properly on the yaourt-side.

**Comment by brenard** [comment]
On Archlinux, _pip_ command seem to be provide by _python-pip_ package :

https://www.archlinux.org/packages/extra/any/python-pip/

**Comment by v1k0d3n** [comment]
i saw that and installed it. ran into other issues...here's some of my output:

root@example-server webvirtmgr]# rm -rf pip_build_root
[root@example-server webvirtmgr]# pip install -r requirements.txt
The temporary folder for building (/tmp/pip_build_root) is either not owned by you, or is a symlink.
pip will not work until the temporary folder is either deleted or is a real directory owned by your user account.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pip/locations.py", line 121, in _get_build_prefix
    os.mkdir(path)
FileExistsError: [Errno 17] File exists: '/tmp/pip_build_root'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==6.1.1', 'console_scripts', 'pip')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/pip/__init__.py", line 13, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/lib/python3.4/site-packages/pip/utils/__init__.py", line 18, in <module>
    from pip.locations import (
  File "/usr/lib/python3.4/site-packages/pip/locations.py", line 151, in <module>
    build_prefix = _get_build_prefix()
  File "/usr/lib/python3.4/site-packages/pip/locations.py", line 142, in _get_build_prefix
    raise exceptions.InstallationError(msg)
pip.exceptions.InstallationError: The temporary folder for building (/tmp/pip_build_root) is either not owned by you, or is a symlink.
[root@example-server webvirtmgr]# rm -rf /tmp/pip_build_root
[root@example-server webvirtmgr]# pip install -r requirements.txt
Collecting django==1.5.5 (from -r requirements.txt (line 1))
  Downloading Django-1.5.5.tar.gz (8.1MB)
    100% |████████████████████████████████| 8.1MB 107kB/s 
Collecting gunicorn==18.0 (from -r requirements.txt (line 2))
  Downloading gunicorn-18.0-py33-none-any.whl (93kB)
    100% |████████████████████████████████| 94kB 4.3MB/s 
Collecting lockfile>=0.9 (from -r requirements.txt (line 5))
  Downloading lockfile-0.10.2.tar.gz
Installing collected packages: django, gunicorn, lockfile
  Running setup.py install for django
  Running setup.py install for lockfile
Successfully installed django-1.5.5 gunicorn-18.0 lockfile-0.10.2
[root@example-server webvirtmgr]# /usr/lib/webvirtmgr/manage.py syncdb
WARNING:root:No local_settings file found.
Creating tables ...
Creating table auth_permission
Creating table auth_group_permissions
Creating table auth_group
Creating table auth_user_groups
Creating table auth_user_user_permissions
Creating table auth_user
Creating table django_content_type
Creating table django_session
Creating table django_site
Creating table servers_compute
Creating table instance_instance
Creating table create_flavor

You just installed Django's auth system, which means you don't have any superusers defined.
Would you like to create one now? (yes/no): yes
Username (leave blank to use 'root'): user01
Email address: user01@domain.org
Password: 
Password (again): 
Superuser created successfully.
Installing custom SQL ...
Installing indexes ...
Installed 6 object(s) from 1 fixture(s)
[root@example-server webvirtmgr]# ./manage.py collectstatic
WARNING:root:No local_settings file found.
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.4/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.4/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.4/site-packages/django/core/management/__init__.py", line 263, in fetch_command
    app_name = get_commands()[subcommand]
  File "/usr/lib/python3.4/site-packages/django/core/management/__init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/lib/python3.4/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.4/site-packages/django/conf/__init__.py", line 48, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3.4/site-packages/django/conf/__init__.py", line 132, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.4/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/usr/lib/webvirtmgr/webvirtmgr/settings.py", line 188, in <module>
    '.secret_key_store'))
  File "/usr/lib/webvirtmgr/webvirtmgr/utils/secret_key.py", line 61, in generate_or_read_from_file
    raise FilePermissionError("Insecure key file permissions!")
webvirtmgr.utils.secret_key.FilePermissionError: Insecure key file permissions!
[root@example-server webvirtmgr]#

**Comment by retspen** [comment]
You use python 3.4 but need python 2.7 because libvirt doesn't support python 3.4

**Comment by v1k0d3n** [comment]
sorry, i was testing and did not put the correct version back into manage.py. this has all come back full circle actually.

<pre>
[root@megatron webvirtmgr]# ./manage.py collectstatic
WARNING:root:No local_settings file found.
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/webvirtmgr/webvirtmgr/settings.py", line 185, in <module>
    from webvirtmgr.utils import secret_key
  File "/usr/lib/webvirtmgr/webvirtmgr/utils/secret_key.py", line 16, in <module>
    import lockfile
ImportError: No module named lockfile
[root@megatron webvirtmgr]# 
</pre>

**Comment by retspen** [comment]
```bash
pip freeze | grep lockfile
```

**Comment by v1k0d3n** [comment]
hmmm...that doesn't return anything. did i perform this wrong or was something missed during installation?

<pre>
[root@megatron webvirtmgr]# pip2.7 freeze | grep lockfile
[root@megatron webvirtmgr]# 
</pre>

**Comment by retspen** [comment]
Your <code>pip</code> app is symlink to <code>pip3.4</code>:

**Comment by retspen** [comment]
```bash
pip2.7 install -r requirements.txt
```

**Comment by v1k0d3n** [comment]
wow...sometimes it's the simplest things. sorry for running you down this road. bit of a dependency misunderstanding on my part; and i really wasn't expecting (or obviously looking out for) it. thank you for your patience and guidance. hopefully others find this dialog useful. you can close out the ticket as I am able to run (and successfully login to) the webvirtmgr interface now.

<pre>
[root@megatron webvirtmgr]# ./manage.py runserver 0:8000
Validating models...

0 errors found
May 13, 2015 - 13:31:17
Django version 1.5.5, using settings 'webvirtmgr.settings'
Development server is running at http://0:8000/
Quit the server with CONTROL-C.
[13/May/2015 13:31:34] "GET / HTTP/1.1" 302 0
[13/May/2015 13:31:34] "GET /login/ HTTP/1.1" 200 2216
[13/May/2015 13:31:34] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 97339
[13/May/2015 13:31:34] "GET /static/css/signin.css HTTP/1.1" 200 780
[13/May/2015 13:31:34] "GET /static/css/webvirtmgr.css HTTP/1.1" 200 3474
[13/May/2015 13:31:34] "GET /static/js/jquery-1.10.2.js HTTP/1.1" 200 273199
[13/May/2015 13:31:34] "GET /static/img/favicon.ico HTTP/1.1" 200 2238
[13/May/2015 13:31:41] "POST /login/ HTTP/1.1" 302 0
[13/May/2015 13:31:41] "GET /servers/ HTTP/1.1" 200 11973
[13/May/2015 13:31:41] "GET /static/css/webvirtmgr.css HTTP/1.1" 304 0
[13/May/2015 13:31:41] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
[13/May/2015 13:31:41] "GET /static/css/table-sort.css HTTP/1.1" 200 424
[13/May/2015 13:31:41] "GET /static/js/jquery-1.10.2.js HTTP/1.1" 304 0
[13/May/2015 13:31:41] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 27726
</pre>
