### ISSUE TITLE
Error import webvirtmgr.settings

### ISSUE THREAD

**Issue by mathiasaulo** [retspen/webvirtmgr#623]
Operation System: CentOS
Server VM: KVM

When placed ./manage.py  collectstatic command appears the error below

./manage.py collectstatic
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 132, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'webvirtmgr.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named webvirtmgr.settings

this is error

I need you help.. thanks

**Comment by Azendale** [comment]
Sorry for the delayed response. It seems like a couple of things could be happening:
- You could be in the wrong directory. Do a `pwd` and an `ls` and share them to give us an idea what directory you were in when this error occurred.
- Are you using a virtual environment for python? Have you run something like `<myvirtualenvironmentname>/bin/activate`

**Comment by mathiasaulo** [comment]
Thanks, virtual environment python with error, redid installation process, some upgrade in the packages and works.

Thanks your patience. =)
